// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Client.Plugins
{
public static class WorldStateClient
{
	[ClientRpc(Class = 2961946757872926779, Function = 550162369879082182)]
	public static void SetWorldState(ulong playerId, uint hours, uint minutes, uint seconds, CName weather, float blend)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteUint32(hours);
			data.WriteUint32(minutes);
			data.WriteUint32(seconds);
			data.WriteUint64(weather.Hash);
			data.WriteFloat(blend);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 2961946757872926779, 550162369879082182, data);
		} finally {
			IBuffer.Release(data);
		}
	}

}
}